version: "3"
services:
  covid:
    image: medblocks/covid-app:v0
    ports:
      - "3000:8080"
    environment:
      - OPENEHR_ENDPOINT=https://ehrbase.course.voiceintern.com
      - FHIR_ENDPOINT=https://fhir-jpa.test4.voiceintern.com